config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :expenses, only: %i[index new create], controller: 'expenses'
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_expenses, dependent: :destroy
  has_many :expenses, through: :category_expenses

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/category_expense.rb
class CategoryExpense < ApplicationRecord
  belongs_to :category
  belongs_to :expense

  validates :expense_id, presence: true
  validates :category_id, presence: true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
  has_many :category_expenses
  has_many :categories, through: :category_expenses

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories
  has_many :expenses

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    categories_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories
    @total_categories_amount = @categories.sum { |category| category.expenses.sum(:amount) }
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      @categories = current_user.categories.all
      redirect_to categories_path
    else
      render html: @category.errors.full_messages
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.category_expenses.destroy_all
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_expense, only: %i[show edit update destroy]

  # GET /expenses or /expenses.json
  def index
    category_id = params[:category_id]
    order = params[:order] || 'desc' # Default to descending order if not provided

    @category = Category.find(category_id)
    @expenses = @category.expenses.order(created_at: order)
  end

  # GET /expenses/1 or /expenses/1.json
  def show; end

  # GET /expenses/new
  def new
    @expense = Expense.new
    @categories = current_user.categories.all
  end

  def create
    @expense = current_user.expenses.build(expense_params)
    if @expense.save
      @expense.category_ids = params[:expense][:category_ids] if params[:expense][:category_ids].present?

      redirect_to category_expenses_path
    else
      render html: @expense.errors.full_messages
    end
  end

  # GET /expenses/1/edit
  def edit; end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy!

    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    params.require(:expense).permit(:name, :amount, :user_id, category_ids: [])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def start; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/categories/index.html.erb
<section class="section">
  <div class="header">
    <div>
      <i class="fas fa-bars"></i>
    </div>
    <h2>Categories</h2>
    <div class="icon-box">
      <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#d6d6d6}</style><path d="M416 208c0 45.9-14.9 88.3-40 122.7L502.6 457.4c12.5 12.5 12.5 32.8 0 45.3s-32.8 12.5-45.3 0L330.7 376c-34.4 25.2-76.8 40-122.7 40C93.1 416 0 322.9 0 208S93.1 0 208 0S416 93.1 416 208zM208 352a144 144 0 1 0 0-288 144 144 0 1 0 0 288z"/></svg>
    </div>
  </div>
  <div class="container">
  <div class="total-transactions">
  <h4>Categories Total: </h4>
    <strong>Categories Total: <%= "$ #{@total_categories_amount}" %></strong>
  </div>
    <ul class="categories">
      <% @categories.each do |category| %>
        <li class="categories-item">
          <div class="icon-box">
            <img src="<%= category.icon %>" alt=""/>
          </div>
          <div class="category-name">
          <%= link_to category.name, category_expenses_path(category_id: category.id, order: 'desc') %>
          </div>
          <div class="category-total">
            <%= "$ #{category.expenses.sum(:amount)}" %>
          </div>
          <%= button_to  category, method: :delete do %>
            <i class="fas fa-trash-alt large-trash-icon"></i>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <%= link_to 'New Category', new_category_path, class: 'btn' %>
</section>

app/views/categories/new.html.erb
<section class="section">
  <div class="header">
    <div>
      <%= link_to categories_path do %>
        <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#ffffff}</style><path d="M512 256A256 256 0 1 0 0 256a256 256 0 1 0 512 0zM271 135c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9l-87 87 87 87c9.4 9.4 9.4 24.6 0 33.9s-24.6 9.4-33.9 0L167 273c-9.4-9.4-9.4-24.6 0-33.9L271 135z"/></svg>
      <% end %>
    </div>
    <h2>New category</h2>
    <div class="icon-box">
      <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#d6d6d6}</style><path d="M416 208c0 45.9-14.9 88.3-40 122.7L502.6 457.4c12.5 12.5 12.5 32.8 0 45.3s-32.8 12.5-45.3 0L330.7 376c-34.4 25.2-76.8 40-122.7 40C93.1 416 0 322.9 0 208S93.1 0 208 0S416 93.1 416 208zM208 352a144 144 0 1 0 0-288 144 144 0 1 0 0 288z"/></svg>
    </div>
  </div>
  <div class="container">
      <%= form_with model: @category, method: :post do |f| %>
        <div class="form-box">
            <div class="field">
              <%= f.text_field :name, placeholder: 'Name', class: 'input' %>
            </div>
            <div class="field">
              <%= f.text_field :icon, placeholder: 'Icon URL', class: 'input' %>
            </div>
            <div class="field">
              <%= f.submit "Add Category", class: 'btn-primary' %>
            </div>
        </div>
      <% end %>
  </div>
</section>

app/views/expenses/index.html.erb
<section class="section">
  <div class="header">
    <div>
      <%= link_to categories_path do %>
        <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#ffffff}</style><path d="M512 256A256 256 0 1 0 0 256a256 256 0 1 0 512 0zM271 135c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9l-87 87 87 87c9.4 9.4 9.4 24.6 0 33.9s-24.6 9.4-33.9 0L167 273c-9.4-9.4-9.4-24.6 0-33.9L271 135z"/></svg>
      <% end %>
    </div>
    <h2>Transactions</h2>
    <div class="icon-box">
      <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#d6d6d6}</style><path d="M416 208c0 45.9-14.9 88.3-40 122.7L502.6 457.4c12.5 12.5 12.5 32.8 0 45.3s-32.8 12.5-45.3 0L330.7 376c-34.4 25.2-76.8 40-122.7 40C93.1 416 0 322.9 0 208S93.1 0 208 0S416 93.1 416 208zM208 352a144 144 0 1 0 0-288 144 144 0 1 0 0 288z"/></svg>
    </div>
  </div>
  <div class="container">
  <div class="total-transactions">
    <h4><%= @category.name %> Total: </h4>
    <strong><%= @expenses.sum(:amount) %></strong>
  </div>
  <ul class="categories">
    <% @expenses.each do |expense| %>
        <li class="transactions-item">
          <div class="icon-box">
            <img src="<%= @category.icon %>"/>
          </div>
          <div class="transaction-desc-box">
            <div class="transaction-name-box">
              <p><%= expense.name %></p>
              <strong><%= expense.amount %></strong>
              </div>
              <div class="creation-box">
              <p><%= DateTime.parse(expense.created_at.to_s).strftime("%d %b %Y") %></p>
              </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
  <%= link_to 'New transaction', new_category_expense_path(@category), class: 'btn' %>
</section>

app/views/expenses/new.html.erb
<section class="section">
  <div class="header">
    <div>
      <%= link_to categories_path do %>
        <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#ffffff}</style><path d="M512 256A256 256 0 1 0 0 256a256 256 0 1 0 512 0zM271 135c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9l-87 87 87 87c9.4 9.4 9.4 24.6 0 33.9s-24.6 9.4-33.9 0L167 273c-9.4-9.4-9.4-24.6 0-33.9L271 135z"/></svg>
      <% end %>
    </div>
    <h2>New Transaction</h2>
    <div class="icon-box">
      <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#d6d6d6}</style><path d="M416 208c0 45.9-14.9 88.3-40 122.7L502.6 457.4c12.5 12.5 12.5 32.8 0 45.3s-32.8 12.5-45.3 0L330.7 376c-34.4 25.2-76.8 40-122.7 40C93.1 416 0 322.9 0 208S93.1 0 208 0S416 93.1 416 208zM208 352a144 144 0 1 0 0-288 144 144 0 1 0 0 288z"/></svg>
    </div>
  </div>
  <div class="container">
  <%= form_with model: @expense, url: category_expenses_path, method: :post do |f|%>
    <div class="form-box">
        <div class="field">
          <%= f.text_field :name, placeholder: 'Name', class: 'input' %>
        </div>
        <div class="field">
          <%= f.text_field :amount, placeholder: 'Amount', class: 'input' %>
        </div>
        <div class="field categories-dropdown">
          <%= f.collection_select :category_ids, @categories, :id, :name, include_blank: 'Select a category', class: 'input' %>
        </div>
        <div class="field">
        <%= f.submit "Add Transaction", class: 'btn-primary' %>
      </div>
    </div>
  <%end %>
  </div>
</section>

app/views/home/index.html.erb
<section class="section-splash">
  <h3>Budget Me <i class="fas fa-piggy-bank"></i></h3>
  <div class="link-box">
    <%= link_to 'LOG IN', new_user_session_path %>
    <%= link_to 'SIGN UP', new_user_registration_path%>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>